version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - restore_cache: # restore the saved cache after the first run or if `pom.xml` has changed
          key: circleci-ticktok-java-client-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline -Dversion=0.0.0 # gets the project dependencies

      - save_cache: # saves the project dependencies
          paths:
            - ~/.m2
          key: circleci-ticktok-java-client-{{ checksum "pom.xml" }}

      - run: mvn test -Dversion=0.0.0

      - run:
          name: destribute to jcneter
          command: .circleci/destribute_to_jcenter.sh
